### ISSUE TITLE
Extension doesn' t work

### ISSUE THREAD

**Issue by shayaulman** [iwehrman/google-search-result-hotkeys#2]
I was so exicited to find this ext, unfortunately it doesn't work.
@iwehrman , is this project still maintained?

If not I would like to make a fork to fiz and maintain it.

**Comment by iwehrman** [comment]
I didn't realize it had broken, but if you submit a PR, I'll merge it and update the Chrome extension. Thanks!

**Comment by shayaulman** [comment]
https://github.com/iwehrman/google-search-result-hotkeys/pull/3/commits/9f473569eb568ad8d30510bf1c212d691d5ac419
